repos:
    # ✅ uv lock file format checker
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.17
    hooks:
      - id: uv-lock


  # ✅ Code formatting
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: [--config=pyproject.toml]


  # ✅ Linting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.7
    hooks:
      - id: ruff
        args: [--config=pyproject.toml]


  # ✅ Basic cleanup
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents, --unsafe]
      - id: name-tests-test
        args: [--pytest-test-first]


  # ✅ Type checking - mypy with all dependencies
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml]
        additional_dependencies:
          - pytest
          - pytest-mypy-plugins
          - pydantic
          - click
          - types-click
          - rich
          - rich-click


  # ✅ Security check
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"] # Point to config if using it
        # You might need to exclude test directories:
        exclude: ^tests/


  # # NOT WORKING
  # # ✅ (Optional) Check requirements.txt/lock files for issues
  # # Dependency Security
  # - repo: https://github.com/pyupio/safety
  #   rev: 3.1.0
  #   hooks:
  #     - id: safety
  #       name: safety check for uv.lock
  #       args: ["check", "--file=uv.lock", "--full-report"]
